@startuml
title Create Review

actor User

participant "Review Service" as Review

database MongoDB

User -> Review

POST /reviews

Review -> MongoDB

Insert Review

MongoDB --> Review

Review --> User

201 Created

@enduml