apiVersion: apps/v1
kind: Deployment

metadata:
  name: producer
  namespace: order-system

spec:
  replicas: 1

  selector:
    matchLabels:
      app: producer

  template:
    metadata:
      labels:
        app: producer

    spec:
      containers:
        - name: producer
          image: producer:1.0
          imagePullPolicy: Never

          ports:
            - containerPort: 8081

          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-kafka-bootstrap.kafka.svc.cluster.local:9092